### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by retorquere** [cronofy/cronofy-ruby#22]
I'm getting this error

```
cronofy-0.14.0/lib/cronofy/errors.rb:93:in `raise_error': 422 Unprocessable Entity (Cronofy::InvalidRequestError)
	from /Users/emile/.rvm/gems/ruby-2.3.0@viewpoint/gems/cronofy-0.14.0/lib/cronofy/errors.rb:86:in `raise_if_error'
	from /Users/emile/.rvm/gems/ruby-2.3.0@viewpoint/gems/cronofy-0.14.0/lib/cronofy/client.rb:762:in `http_get'
	from /Users/emile/.rvm/gems/ruby-2.3.0@viewpoint/gems/cronofy-0.14.0/lib/cronofy/client.rb:756:in `get_page'
	from /Users/emile/.rvm/gems/ruby-2.3.0@viewpoint/gems/cronofy-0.14.0/lib/cronofy/client.rb:730:in `initialize'
	from /Users/emile/.rvm/gems/ruby-2.3.0@viewpoint/gems/cronofy-0.14.0/lib/cronofy/client.rb:196:in `new'
	from /Users/emile/.rvm/gems/ruby-2.3.0@viewpoint/gems/cronofy-0.14.0/lib/cronofy/client.rb:196:in `read_events'
	from ./us.rb:11:in `<main>'

```

when I run this script

```
require 'cronofy'

cronofy = Cronofy::Client.new(access_token: TOKEN)

cronofy.read_events(from: (Date.today - 365)).each{|event|
  puts event
}
```

**Comment by gshutler** [comment]
Hi @retorquere you can only [read events](https://www.cronofy.com/developers/api/#read-events) up to 42 days in the past.
