### ISSUE TITLE
error running specs?

### ISSUE THREAD

**Issue by railsjedi** [cronofy/cronofy-ruby#9]
is there a missing gem dependency for running specs?

```
[jc@mac ~/Gems/cronofy-ruby(fix-inspect)] rake
/Users/jc/.rvm/rubies/ruby-2.1.5/bin/ruby -I/Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib:/Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-support-3.3.0/lib /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --color
/Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/formatters.rb:172:in `find_formatter': Formatter 'nested' unknown - maybe you meant 'documentation' or 'progress'?. (ArgumentError)
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/formatters.rb:140:in `add'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:752:in `add_formatter'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:114:in `block in load_formatters_into'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:114:in `each'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:114:in `load_formatters_into'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:23:in `configure'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:101:in `setup'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
/Users/jc/.rvm/rubies/ruby-2.1.5/bin/ruby -I/Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/lib:/Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-support-3.3.0/lib /Users/jc/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --color failed
```

**Comment by railsjedi** [comment]
nm, user error

**Comment by gshutler** [comment]
For what it's worth, running `script/ci` provides a consistent way to run the specs.
